# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IiG3sOETOszqBfL_DAiDRPWy-gq_oWf_
"""

import pandas as pd
import json
import requests

scrape_url="https://api.sofascore.com/api/v1/unique-tournament/1900/season/45661/standings/total"
req=requests.get(scrape_url)
json_obj=json.loads(req.content)

type(json_obj)

json_obj.keys()

len(json_obj)

json_obj["standings"]

type(json_obj["standings"])

json_obj["standings"][0]

type(json_obj["standings"][0])

len(json_obj["standings"][0])

json_obj["standings"][0].keys()

json_obj["standings"][0]["rows"]

pd.json_normalize(json_obj["standings"][0]["rows"])

isl_data_df=pd.json_normalize(json_obj["standings"][0]["rows"])

from google.colab import files
isl_data_df.to_csv('isl_data.csv')
files.download('isl_data.csv')